# Default values for kubevela.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section Core parameters

## @param systemDefinitionNamespace System definition namespace, if unspecified, will use built-in variable `.Release.Namespace`.
systemDefinitionNamespace:

## @param concurrentReconciles concurrentReconciles is the concurrent reconcile number of the controller
concurrentReconciles: 4
## @param ignoreWorkflowWithoutControllerRequirement will determine whether to process the workflowrun without 'workflowrun.oam.dev/controller-version-require' annotation
ignoreWorkflowWithoutControllerRequirement: false

## @section KubeVela workflow parameters

## @param workflow.enableSuspendOnFailure Enable the capability of suspend an failed workflow automatically
## @param workflow.enablePatchStatusAtOnce Enable the capability of patch status at once
## @param workflow.enableWatchEventListener Enable the capability of watch event listener for a faster reconcile, note that you need to install [kube-trigger](https://github.com/kubevela/kube-trigger) first to use this feature
## @param workflow.backoff.maxTime.waitState The max backoff time of workflow in a wait condition
## @param workflow.backoff.maxTime.failedState The max backoff time of workflow in a failed condition
## @param workflow.step.errorRetryTimes The max retry times of a failed workflow step
workflow:
  enableSuspendOnFailure: false
  enablePatchStatusAtOnce: false
  enableWatchEventListener: false 
  backoff:
    maxTime:
      waitState: 60
      failedState: 300
  step:
    errorRetryTimes: 10

## @section KubeVela workflow backup parameters

## @param backup.enabled Enable backup workflow record
## @param backup.strategy The backup strategy for workflow record
## @param backup.ignoreStrategy The ignore strategy for backup
## @param backup.cleanOnBackup Enable auto clean after backup workflow record
## @param backup.groupByLabel The label used to group workflow record
## @param backup.persistType The persist type for workflow record
## @param backup.configSecretName The secret name of backup config
## @param backup.configSecretNamespace The secret name of backup config namespace
backup:
  enabled: false
  strategy: BackupFinishedRecord
  ignoreStrategy: IgnoreLatestFailedRecord
  cleanOnBackup: false
  groupByLabel: ""
  persistType: ""
  configSecretName: "backup-config"
  configSecretNamespace: "vela-system"

## @section KubeVela Workflow controller parameters

## @param replicaCount Workflow controller replica count
replicaCount: 1

## @param imageRegistry Image registry
imageRegistry: ""
## @param image.repository Image repository
## @param image.tag Image tag
## @param image.pullPolicy Image pull policy
image:
  repository: oamdev/vela-workflow
  tag: latest
  pullPolicy: Always

## @param resources.limits.cpu Workflow controller's cpu limit
## @param resources.limits.memory Workflow controller's memory limit
## @param resources.requests.cpu Workflow controller's cpu request
## @param resources.requests.memory Workflow controller's memory request
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 20Mi

## @param webhookService.type KubeVela webhook service type
## @param webhookService.port KubeVela webhook service port
webhookService:
  type: ClusterIP
  port: 9443

## @param healthCheck.port KubeVela health check port
healthCheck:
  port: 9440


## @section Common parameters

## @param imagePullSecrets Image pull secrets
imagePullSecrets: []
## @param nameOverride Override name
nameOverride: ""
## @param fullnameOverride Fullname override
fullnameOverride: ""

## @param serviceAccount.create Specifies whether a service account should be created
## @param serviceAccount.annotations Annotations to add to the service account
## @param serviceAccount.name The name of the service account to use. If not set and create is true, a name is generated using the fullname template
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

## @skip podSecurityContext
podSecurityContext: {}
  # fsGroup: 2000

## @skip securityContext
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## @param nodeSelector Node selector
nodeSelector: {}

## @param tolerations Tolerations
tolerations: []

## @param affinity Affinity
affinity: {}

## @param rbac.create Specifies whether a RBAC role should be created
rbac:
  create: true

## @param logDebug Enable debug logs for development purpose
logDebug: false

## @param logFilePath If non-empty, write log files in this path
logFilePath: ""

## @param logFileMaxSize Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited.
logFileMaxSize: 1024

## @skip admissionWebhooks
admissionWebhooks:
  enabled: true
  failurePolicy: Fail
  certificate:
    mountPath: /etc/k8s-webhook-certs
  patch:
    enabled: true
    image:
      repository: oamdev/kube-webhook-certgen
      tag: v2.4.1
      pullPolicy: IfNotPresent
    nodeSelector: {}
    affinity: {}
    tolerations: []
  certManager:
    enabled: false

## @param kubeClient.qps The qps for reconcile clients, default is 50
## @param kubeClient.burst The burst for reconcile clients, default is 100
## @param kubeClient.userAgent The user agent of the client, default is vela-workflow
kubeClient:
  qps: 500
  burst: 1000
  userAgent: vela-workflow
