apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: test-http-secret
  namespace: "http-secret-e2e-test"
spec:
  workflowSpec:
    steps:
    - name: call-mock-server
      type: request
      properties:
        url: http://mock-server.http-secret-e2e-test.svc.cluster.local/validate
        method: GET
        headersFromSecret:
        - name: Authorization
          secret: api-creds
          key: token
