apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: test-http-secret
  namespace: "http-secret-e2e-test"
spec:
  workflowSpec:
    steps:
    - name: call-httpbin
      type: request
      properties:
        url: http://httpbin.http-secret-e2e-test.svc.cluster.local/headers
        method: GET
        headersFromSecret:
        - name: Authorization
          secret: api-creds
          key: token
      outputs:
      - name: authHeader
        valueFrom: response.headers.Authorization
    - name: verify-header
      type: assert-equal
      inputs:
      - from: authHeader
        parameterKey: actual
      properties:
        expected: "Bearer sk-supersecret-12345"
