name: PostSubmit

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  GO_VERSION: '1.19'

jobs:

  detect-noop:
    runs-on: ubuntu-20.04
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.mdx", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false

  image-multi-arch:
    runs-on: ubuntu-20.04
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    strategy:
      matrix:
        arch: [ amd64, arm64 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build Image
        run: |
          IMG_TAG=latest-${{ matrix.arch }} \
          OS=linux \
          ARCH=${{ matrix.arch }} \
            make docker-build
      - name: Push Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push oamdev/vela-workflow:latest-${{ matrix.arch }}
          docker push oamdev/vela-workflow:latest-${{ matrix.arch }}
  image-manifest:
    runs-on: ubuntu-latest
    needs: [ image-multi-arch ]
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create Manifest
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker manifest create oamdev/vela-workflow:latest \
            oamdev/vela-workflow:latest-amd64 \
            oamdev/vela-workflow:latest-arm64
      - name: Annotate Manifest
        run: |
          docker manifest annotate oamdev/vela-workflow:latest \
            oamdev/vela-workflow:latest-amd64 --arch amd64
          docker manifest annotate oamdev/vela-workflow:latest \
            oamdev/vela-workflow:latest-arm64 --arch arm64
      - name: Push Manifest
        run: |
          docker manifest push oamdev/vela-workflow:latest